### ISSUE TITLE
SNMPv3 discovery dispatch problem

### ISSUE THREAD

**Issue by andlew** [jhthorsen/mojo-snmp#8]
It seems to be a problem with the asyncron handling of the discovey pdu for snmp v3. It work just fine with Net::SNMP alone, both blocked and non-blocked. A workaround I did was to force the _perform_discovery to handle this specific pdu blocked by removing condition for snmp_dispatcher.

**Comment by jhthorsen** [comment]
This is fixed in d26de81 and ff9d579, but it seems like the order of response is not the same as the order of request. At least not on my mac, with snmpd 5.6.2.1.

Not sure if this cause issues or not. It is possible to see the change here: 4ed19b0.

Please let me know if I should still make a new release or if you want me to test more.

**Comment by jhthorsen** [comment]
Travis seems happy now after the 4ed19b0 fix.

https://travis-ci.org/jhthorsen/mojo-snmp/builds/91821696
